#!/usr/bin/env bash

cd "$(dirname "$0")/../"

now=$(date +%s)

function do_backup() {
    shopt -s dotglob

    mkdir -p "$HOME/.backups/$now"

    for file in *; do
        [ -f "$HOME/$file" ] && cp -r "$HOME/$file" "$HOME/.backups/$now/$file"
    done
}

function do_sync() {
    rsync --exclude ".git/" --exclude ".gitmodules"
          --exclude ".DS_Store" \
          --exclude "script/" --exclude "README.md" -av . ~
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
    do_sync
else
    echo "This may overwrite existing files in your home directory,"
    echo "a backup will be saved in \`~/.backups/$now\`."

    read -p "Are you sure? (y/n) " -n 1
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        do_backup
        do_sync
    fi
fi

unset do_sync
unset do_backup
unset now

# Reaload bash_profile
source ~/.bash_profile