#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Allow versioned formulae
brew tap homebrew/versions

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH.
brew install coreutils

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew install homebrew/dupes/grep
brew install homebrew/dupes/less

# Install latest version of bash shell
# Don't forget to change shell to $(brew --prefix bash)/bin/bash.
brew install bash

# Install fish shell, trying to transition to fish from bash
brew install fish

# Install completion (dotfiles completions need this)
brew install bash-completion2

# Install everything else
brew install git
brew install htop
brew install node
brew install go
brew install ssh-copy-id
brew install nmap
brew install resty
brew install tree
brew install mtr
brew install autojump
brew install vim
brew install tmux
brew install the_silver_searcher
brew install grep
brew install less
brew install pv
brew install ansible
brew install heroku-toolbelt
brew install diff-so-fancy

brew install homebrew/completions/vagrant-completion

# Remove outdated versions from the cellar
brew cleanup
