#!/usr/bin/env bash

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x Homebrew not found. Please install it:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep
brew install homebrew/dupes/less

# Install completion (dotfiles completions need this)
brew install bash-completion

# Install latest version of bash shell
brew install bash
echo "Don't forget to change shell to $(brew --prefix bash)/bin/bash."

# Install everything else
brew install git
brew install htop
brew install node
brew install ssh-copy-id
brew install nmap
brew install resty
brew install tree
brew install mtr
brew install z
brew install vim
brew install tmux
brew install the_silver_searcher
brew install ack
brew install grep
brew install less

# Remove outdated versions from the cellar
brew cleanup
